steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/employees-app", "."]

  # Push the image to Google Artifact Registry or Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/employees-app"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "deploy", "employees-app",
      "--image", "gcr.io/$PROJECT_ID/employees-app",
      "--region", "us-central1",
      "--platform", "managed",
      "--allow-unauthenticated"
    ]

# Set Cloud Build to use the latest logs
options:
  logging: CLOUD_LOGGING_ONLY
