steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'backup_function',
    '--runtime=python311',
    '--trigger-http', 
    '--entry-point=backup_function',
    '--source=backup_feature/backup_function/',
    '--region=us-central1']

# Set Cloud Build to use the latest logs
options:
  logging: CLOUD_LOGGING_ONLY